Remove legacy post-update script

diff --git a/fulcrum/hooks/pre-start b/fulcrum/hooks/pre-start
--- a/fulcrum/hooks/pre-start
+++ b/fulcrum/hooks/pre-start
@@ -1,5 +1,12 @@
 #!/usr/bin/env bash
 
+# Remove legacy post-update hook if present
+POST_UPDATE_HOOK="$(readlink -f $(dirname "${BASH_SOURCE[0]}") )/post-update"
+if [[ -e "${POST_UPDATE_HOOK}" ]]; then
+  echo "App: ${APP_ID} - Removing '${POST_UPDATE_HOOK}'"
+  rm -f -- "${POST_UPDATE_HOOK}" || echo "App: ${APP_ID} - Warning: failed to remove '${POST_UPDATE_HOOK}'"
+fi
+
 # If ${APP_DATA_DIR}/data/fulcrum-logs doesn't exist, we create it and set 1000:1000 ownership
 if [[ ! -d "${APP_DATA_DIR}/data/fulcrum-logs" ]]; then
   mkdir -p "${APP_DATA_DIR}/data/fulcrum-logs"
